context:
  name: abb_libegm
  version: 1.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ros-industrial/abb_libegm
  rev: 2c9350abfb67131cae796805fed8cd6eeb2ab7f9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libprotobuf 3.21.* # main dependency for ABB EGM
    - boost
  run:
    - libprotobuf 3.21.*

tests:
  - package_contents:
      lib:
        - abb_libegm
      include:
        - abb_libegm/egm_base_interface.h
        - abb_libegm/egm_controller_interface.h

